airbnb:
  outputs:
    dev:
      type: snowflake
      account: jewgttz-qw49890
      user: dbt

      role: TRANSFORM
      private_key_path: /Users/mohamedsebabti/DBT_CORE/course/rsa_key.p8

      database: AIRBNB
      schema: DEV
      threads: 4
      warehouse: COMPUTE_WH
  target: dev
